### ISSUE TITLE
[Bug] Cannot use geSuiteBan commands from console

### ISSUE THREAD

**Issue by Hatventures** [Cube-Space/geSuit#11]
Step 1: ban myself: /ban dimensionZ75

Step 2: login on the console and type:
unban dimensionZ75

Step 3: exception thrown:

[08:34:15 WARN]: Exception in thread "Craft Scheduler Thread - 18"
[08:34:15 WARN]: org.apache.commons.lang.UnhandledException: Plugin geSuitBans v0.1.0b-3 generated an exception while executing task 681
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at net.cubespace.geSuitBans.tasks.PluginMessageTask.run(PluginMessageTask.java:19)
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:67)
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

Step 4: cry? :P

Good luck. And more will probably come you way buddy

**Comment by geNAZt** [comment]
Erm there was no Player on that Server. No luck for you Sir

**Comment by Hatventures** [comment]
Bah duh. Of course. Sowwy.
