### ISSUE TITLE
UUID Spam

### ISSUE THREAD

**Issue by deathknight842** [Cube-Space/geSuit#43]
Hello, Im having a problem with the console getting this error every time someone joins.
It doesn't matter rather they are cracked or premium, it will gives the same error. 

And I noticed that as long as the user does not exit their minecraft game, then if they disconnect and reconnect the error does not appear. 

The error doesn't seen to affect anything other than just console spam, Unfortunately I'm a little OCD with making sure my log stays error free. 

-------------------------------------------------[ERROR]------------------------------------------------
28.04 04:05:09 [Multicraft] Skipped 48 lines due to rate limit (30/s)
28.04 04:05:08 [Server] SEVERE at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778)
28.04 04:05:08 [Server] SEVERE at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617)
28.04 04:05:08 [Server] SEVERE at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169)
28.04 04:05:08 [Server] SEVERE at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237)
28.04 04:05:08 [Server] SEVERE at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1041)
28.04 04:05:08 [Server] SEVERE at com.mysql.jdbc.Util.getInstance(Util.java:386)
28.04 04:05:08 [Server] SEVERE at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
28.04 04:05:08 [Server] SEVERE at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
28.04 04:05:08 [Server] SEVERE at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
28.04 04:05:08 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
28.04 04:05:08 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
28.04 04:05:08 [Server] SEVERE com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'uuid' cannot be null

**Comment by jimmikaelkael** [comment]
If your bungeecord run in offline mode, you need to set OverwriteUUIDs to true in the config.

**Comment by deathknight842** [comment]
It is set to true.

**Comment by deathknight842** [comment]
I'm going to do a purge of all my MySql data and using a new database. Hopefully that will fix it.
